import './globals.css'
import { Inter } from 'next/font/google'
import NavigationBar from '@/components/navigationBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My NextJS App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {

  return (
    <html 
      className="bg-cyan-400"
      lang="en"
    >
      <body className={`${inter.className} pb-[5rem]`}>

        <NavigationBar />

        {children}

      </body>

    </html>
  )
}
